### DISCUSSION TITLE
Text color

### DISCUSSION THREAD

**Discussion by nashaden** [LesTR/homeassistant-minimalistic-area-card#202] [Q&A] [answered]
Hi. First of all I must say that this card of yours is the reason why I finally started redesigning my mobile dashboard. Up till now I've been using mushroom cards. Anyway, is it possible to change the color of the texts displayed on the card, like the values of the sensors and the area name? I know the texts change from white to black when using either dark or light mode, but I am not a big fan of dark mode and unfortunately in light mode the text is black which does not look good on most pictures used as card's background.

**Comment by LesTR** [comment, marked as answer]
Hi @nashaden, sorry for the late reply, for some reason, I was not notified.

Yes, there was an issue with the light mode. It should be fixed, but it uses the general template variables. Example:
<img width="260" alt="image" src="https://github.com/user-attachments/assets/89ba2669-dfae-426c-abc8-99de8ce120bd" />


I agree, it can look bad when there is some picture, for example:

<img width="510" alt="image" src="https://github.com/user-attachments/assets/186462e2-2bed-410d-81bb-f90b1ab68db1" />

There was some discussion in [issue-216](https://github.com/LesTR/homeassistant-minimalistic-area-card/issues/216), and I added some new options in the linked PRs. That means you can now use, for example, `style.color: white`, here is the output:

<img width="475" alt="image" src="https://github.com/user-attachments/assets/c844f08f-4386-478a-95aa-2421bb7f8969" />

You can set it on the card level:
```yaml
type: custom:better-minimalistic-area-card
title: Bathroom
area: bathroom
image: /local/images/bart.jpg
hide_unavailable: false
show_area_icon: true
shadow: true
force_dialog: false
style:
  color: white
```

or globally via CSS template variable `--ha-better-minimalistic-area-card-color`.

It can be specified more granularly via:
- `--ha-better-minimalistic-area-card-color` - configure color for text, sensors, buttons and state values
- `--ha-better-minimalistic-area-card-sensors-color` - configure color for sensors and state values in the sensor area
- `--ha-better-minimalistic-area-card-buttons-color` - configure color for buttons and state values in the button area
- `--ha-better-minimalistic-area-card-shadow-color` - configure color of shadow (when enabled) 

Or on the card level via:
```yaml
style:
    color: red # Override the color for text and icons (optional)
    sensors_color: blue #Override the color for sensors (optional)
    buttons_color: blue #Override the color for buttons (optional)
    background_color: yellow # a color name, rgb hex or rgba function when an image is not provided (optional)
    shadow_color: grey # a color name, rgb hex or rgba function for shadow when enabled
```

Feel free to let me know if you have any questions or suggestions for improvement.
