### ISSUE TITLE
[Bug]: Small misalignment btw. sensor icon and highlighted clickable area

### ISSUE THREAD

**Issue by RkcCorian** [LesTR/homeassistant-minimalistic-area-card#116]
### What happened?

Small misalignment btw. sensor icon and highlighted clickable area. The same is visible in the version from junalmeida.

I marked in the following screenshot the highlighted clickable area with a small orange circle.

![image](https://github.com/user-attachments/assets/d1d975cb-653c-467b-b2a9-7dbab4a45317)

Many thanks for fixing upfront!

### Card Version

1.2.18

### Home Assistant Version

13.2

### Browser Version

Edge v.130.0.2849.56 (Offizielles Build) (64-Bit)

### Relevant card config

```yaml
type: custom:minimalistic-area-card
title: Schlafzimmer
area: Schlafzimmer
image: /local/pictures/rooms/Schlafzimmer.jpg
hide_unavailable: false
state_color: true
darken_image: true
shadow: false
entities:
  - entity: light.schlafzimmerbeleuchtung
    tap_action:
      action: more-info
    double_tap_action:
      action: toggle
  - entity: cover.schlafzimmerrollladen
  - entity: sensor.schlafzimmerthermostat_humidity
    state_color: false
    color: "#2196F3"
  - entity: sensor.schlafzimmerthermostat_temperature
    state_color: false
    color: "#FF6F22"
  - entity: binary_sensor.schlafzimmerfenster
card_mod:
  style: |
    .box .card-header {
      font-weight: normal !important;
    }
layout_options:
  grid_columns: 2
  grid_rows: 2
```

**Comment by LesTR** [comment]
You are right, it's messy
<img width="496" alt="image" src="https://github.com/user-attachments/assets/e1fe194d-3d31-47f9-b937-af7b641991ba">

I'm not a frontend expert, but I'll try to fix it.

**Comment by LesTR** [comment]
Ok, the issue is caused by [this zoom](https://github.com/LesTR/homeassistant-minimalistic-area-card/blob/v1.2.18/src/minimalistic-area-card.ts#L752), I just don't find the proper solution yet.

**Comment by RkcCorian** [comment]
Many many thanks!! I hope you find a solution 😊

**Comment by LiquidPT** [comment]
Hrmm, this might be something I could look into.

**Comment by LesTR** [comment]
I would say this will be a very simple change for someone who knows CSS, but that's not me, sorry :D The whole issue is with the linked zoom usage, but I already spent some time on that and wasn't able to make the sensors icon smaller

**Comment by RkcCorian** [comment]
> Hrmm, this might be something I could look into.

Many thanks upfront!!

**Comment by RkcCorian** [comment]
@LesTR : Many thanks! But I installed v1.2.34 and it is not fixed for me 🙈

**Comment by LesTR** [comment]
@RkcCorian hmm, it does for me

<img width="237" alt="Image" src="https://github.com/user-attachments/assets/4e620892-949d-4f8d-b859-4f55d4a00187" />

This is a screen when I added:
```yaml
card_mod:
  style: |
    div.sensors ha-icon-button {
      border: 1px solid red;
    }
```

The "clickable" area is directly inside the box, this was not the case before.
