### ISSUE TITLE
[Bug]: Icon not showing

### ISSUE THREAD

**Issue by LiquidPT** [LesTR/homeassistant-minimalistic-area-card#127]
### What happened?

I added the icon as instructed and it just makes a blank space next to the title. I'm using a Sections layout on the view

### Card Version

1.2.0

### Home Assistant Version

2024.11.0

### Browser Version

Edge 130.0.2849.80 

### Relevant card config

```yaml
type: custom:minimalistic-area-card
title: Living Room
area: living_room
hide_unavailable: true
state_color: true
icon: mdi-sofa
tap_action:
  action: navigate
  navigation_path: /dashboard-cameras/living-room
entities:
  - switch.xmas_tree
  - light.living_room
  - sensor.living_room_temperature
  - sensor.living_room_wallmote_quad_battery
  - binary_sensor.magic_areas_presence_tracking_living_room_area_state
grid_options:
  columns: 12
  rows: 2
```
