### ISSUE TITLE
[FR]: In-Line light & media Entities

### ISSUE THREAD

**Issue by oerix** [LesTR/homeassistant-minimalistic-area-card#148]
### What happened?

At the moment the Light/Media entities are automatically shown in the lower right corner of the button, however it would be great if you could add an option to put them in-line with the other sensor entities below the header title.

I'm trying to condense the card as much as possible, but currently it's not possible for these entities by design.

Thanks

### Card Version

1.2.18

### HomeAssistant Version

2024.12.2

**Comment by LesTR** [comment]
This can be configured in the `section` attribute.

SMT like:
```yaml
- entity: light.stairs_leds
  icon: mdi:stairs
  section: sensors
```

**Comment by LesTR** [comment]
> how would I adjust the icon sizes for the sections?

You probably need to reset these[ two zoom settings.](https://github.com/LesTR/homeassistant-minimalistic-area-card/blob/main/src/minimalistic-area-card.ts#L751)

So, smt like:
```css
.box .sensors ha-icon-button {
    -moz-transform: scale(1) !important;
    zoom: 1 !important;
}
``` 
For the state values, it's [this settings](https://github.com/LesTR/homeassistant-minimalistic-area-card/blob/main/src/minimalistic-area-card.ts#L702)

> Also, it would great if you could add 'card_mod' attributes in the Readme file.

I think this is very specific to your needs and it's not generic, but I can at least describe the possible modifications and the CSS model/classes.
