### ISSUE TITLE
[Question]: Is show_area_icon intended to use the icon from the area

### ISSUE THREAD

**Issue by LiquidPT** [LesTR/homeassistant-minimalistic-area-card#178]
### What happened?

I have icons defined for each of my areas. In the past I also defined (the same) icon in the minimalistic-area-card. I saw the show_area_icon attribute and replaced my icon definition with it, expecting it to pick up the area icon, but it didn't.

Is this just a visibility switch for the icon defined in the card (in which case I think it's poorly named, but likely not needed since you could just not define an icon), or is it supposed to pick up the icon from the referenced area (in which case, this is a bug)

### Card Version

1.2.20

### HomeAssistant Version

2025.1.3

### Relevant card config

```yaml
type: custom:better-minimalistic-area-card
title: Living Room
area: living_room
hide_unavailable: true
state_color: true
show_area_icon: true
tap_action:
  action: navigate
  navigation_path: /dashboard-panel/living-room
entities:
  - switch.xmas_tree
  - light.living_room
  - sensor.living_room_temperature
  - sensor.living_room_wallmote_quad_battery
  - binary_sensor.magic_areas_presence_tracking_living_room_area_state
grid_options:
  columns: 12
  rows: 2
```

### Relevant log output

```shell

```
