### ISSUE TITLE
[Bug]: Image is not displayed

### ISSUE THREAD

**Issue by M3te0r** [LesTR/homeassistant-minimalistic-area-card#183]
### What happened?

Hi,
I've been following the documentation to setup the card, it works great but I have an issue with no images displaying at all, wherever its source is, local image (/local/images - /config/www/images), remote URL, from image entity etc

I've tested with an image card to see if there was a problem with the file, but with the image card, it's displayed correctly
Here are screenshots of my cards settings

![Image](https://github.com/user-attachments/assets/6d441703-8acb-40dd-a8b4-c14cdad6907f)
![Image](https://github.com/user-attachments/assets/ca8d2dc0-4607-4f9d-a12e-7b5564b237a4)
![Image](https://github.com/user-attachments/assets/95059c54-3f07-4788-8bf4-b697ed108d6c)

### Card Version

v1.2.22

### Home Assistant Version

2025.01

### Browser Version

Firefox 134.0.2

### Relevant card config

```yaml
type: custom:better-minimalistic-area-card
title: Salon
area: salon
icon: mdi:sofa
image: /local/images/EldenRingVatyvidiaRadhan.png
hide_unavailable: false
background_color: yellow
show_area_icon: true
shadow: true
state_color: true
entity_type: auto
align:
  title: left
  sensors: left
  buttons: right
  title_entities: right
entities:
  - light.switch_bureau
  - light.lampe_rgbw_bureau_pc
  - light.ruban_led_rgb_sous_bureau
  - light.ruban_led_rgb_pc_backlight
  - binary_sensor.everything_presence_cstm_office_mmwave
  - sensor.capteur_temperaure_humidite_bureau_temperature
  - sensor.capteur_temperaure_humidite_bureau_humidity
grid_options:
  rows: 3
  columns: 9
```

### Relevant javascript log output

```shell

```
