### ISSUE TITLE
[Bug]: Background color applied only on border

### ISSUE THREAD

**Issue by DevLn** [LesTR/homeassistant-minimalistic-area-card#186]
### What happened?

This fix "[181] Some icons are not visible in light mode" makes the background color to be only on the card border.
When no picture is set, it's expected to show the background color on entire card.

### Card Version

1.2.23

### Home Assistant Version

2025.1.4

### Browser Version

Chrome(Windows)/Chrome(Android)/Edge/...

### Relevant card config

```yaml
type: custom:better-minimalistic-area-card
title: Test
area: test
show_area_icon: true
background_color: rgba(200, 200, 200, 0.5)
shadow: true
state_color: true
entities:
  - entity: binary_sensor.test
    section: title
grid_options:
  columns: 6
  rows: 2
```

### Relevant javascript log output

```shell

```
