### ISSUE TITLE
[Bug]: State value does not work

### ISSUE THREAD

**Issue by pauldcomanici** [LesTR/homeassistant-minimalistic-area-card#196]
### What happened?

Having this part if the entities:
```
entity: input_boolean.vacuum_auto_start_enabled
    state_color: true
    state:
      - value: "off"
        icon: mdi:door
        hide: true
```
the hide does not happen and I also tested the icon and the icon does not get updated.

Tested in developer templates:
```
{{ states('input_boolean.vacuum_auto_start_enabled')=='off' }}
```
and the result is `True`

### Card Version

1.2.0

### Home Assistant Version

2024.12.3

### Browser Version

Firefox 134.0.1

### Relevant card config

```yaml
type: custom:minimalistic-area-card
title: 0.BC
area: bucatarie
background_color: none
shadow: true
hide_unavailable: false
state_color: true
tap_action:
  action: navigate
  navigation_path: /house-rooms/0bc
entities:
  - entity: input_boolean.vacuum_auto_start_enabled
    state_color: true
    state:
      - value: "off"
        icon: mdi:door
        hide: true
  - entity: sensor.0_bc_snzb_temperature
  - entity: sensor.0_bc_snzb_humidity
  - entity: switch.0_bc_fridge
    icon: mdi:power-socket-eu
    tap_action:
      action: more-info
  - entity: switch.0_bc_light_switch
    icon: mdi:lightbulb-group
grid_options:
  columns: 6
  rows: 2
```

### Relevant javascript log output

```shell

```

**Comment by LesTR** [comment]
Hmm, this should work, are you sure you are using the card from my fork? The version `1.2.0` looks weird - the latest is `1.2.25` also, the type `custom:minimalistic-area-card` is from the original card and deprecated here.

**Comment by pauldcomanici** [comment]
Thank you very much, I don't know how, but I confused myself in the names/repos. Thank you, the issue was solved once I updated to `custom: better-minimalistic-area-card`

**Comment by LesTR** [comment]
No problem, btw you don't need to use the state overrides in this case.
```yaml
entities:
- entity: input_boolean.vacuum_auto_start_enabled
  hide: '${state == "off"}'
```
This should does the same.

**Comment by pauldcomanici** [comment]
Thank you. I already use the hide to link with another entity state:
```
entities:
  - entity: input_boolean.vacuum_auto_start_enabled
    state_color: true
    state:
      - value: "on"
        hide: true
    hide: ${hass.states['vacuum.0bc_roborock_s7_maxv'].state !== 'docked'}
```
