### ISSUE TITLE
[Bug]:  my card does not want to display

### ISSUE THREAD

**Issue by philou669** [LesTR/homeassistant-minimalistic-area-card#208]
### What happened?

all cards work after the update from custom:minimalistic-area-card to custom:better-minimalistic-area-card All cards work after the update except this one! and I don't know why.

help me please Thanks

type: custom:better-minimalistic-area-card
title: Living room
area: Living room
hide_unavailable: false
tap_action:
  action: navigate
  navigation_path: /lovelace/living-room
entities:
  - entity: climate.thermostat_living_room
  - entity: climate.heat_pump_living_room
  - entity: switch.living_room_ceiling_fan_light
    icon: mdi:ceiling-fan-light
  - entity: light.tv_living_room
  - entity: sensor.living_room_temperature
  - entity: sensor.living_room_humidity
  - entity: switch.purificator_living_room
  - entity: binary_sensor.movement_living_room_occupancy

### Card Version

1.2.25

### Home Assistant Version

2025.1.4

### Browser Version

Chrome 132.0.6834.160 (Build officiel) (64 bits)

### Relevant card config

```yaml
type: custom:better-minimalistic-area-card
title: Living room
area: Living room
hide_unavailable: false
tap_action:
  action: navigate
  navigation_path: /lovelace/living-room
entities:
  - entity: climate.thermostat_living_room
  - entity: climate.heat_pump_living_room
  - entity: switch.living_room_ceiling_fan_light
    icon: mdi:ceiling-fan-light
  - entity: light.tv_living_room
  - entity: sensor.living_room_temperature
  - entity: sensor.living_room_humidity
  - entity: switch.purificator_living_room
  - entity: binary_sensor.movement_living_room_occupancy
```

### Relevant javascript log output

```shell

```
