### ISSUE TITLE
[Question]: Possibility to template content

### ISSUE THREAD

**Issue by ikomtur** [LesTR/homeassistant-minimalistic-area-card#212]
### What happened?

Hello
Perhaps this feature already exists and I did not find this in the description.

Im searching for 2 possibilities:
1. override content of the entity state. Say, I want to show an empty string instead of the state

<img width="521" alt="Image" src="https://github.com/user-attachments/assets/25ded8f2-f0bf-4da4-8386-f2b62bcb6910" />

2. to template content in the same way we do inside a chip card. The intention is to place the highlighted content inside the area card.

<img width="537" alt="Image" src="https://github.com/user-attachments/assets/cf484041-7396-497d-9f01-ec9a95d98198" />

### Card Version

1.2.21

### HomeAssistant Version

2025.1.3

### Relevant card config

```yaml
type: custom:better-minimalistic-area-card
title: Bedroom
area: bedroom
shadow: false
darken_image: true
tap_action:
  action: navigate
  navigation_path: "#bedroom"
entities:
  - entity: sensor.a4c138066197_temperature
  - entity: sensor.a4c138066197_humidity
  - entity: light.aqara_smart_wall_switch_e1_no_neutral_single_rocker_2_switch
  - entity: binary_sensor.bedroom_lights_state
    state:
      - value: "on"
        color: orange
        icon: mdi:lightbulb
        hide: false
      - value: "off"
        hide: true
  - entity: binary_sensor.window_sensor_01_opening
    state:
      - value: "on"
        color: white
        hide: false
      - value: "off"
        color: white
        hide: true
    tap_action:
      action: navigate
      navigation_path: "#bedroom"
```

### Relevant log output

```shell

```
