### ISSUE TITLE
[Bug]: Buttons which are off / closed are not in gray as expected, but white. After some time randomly going to target gry

### ISSUE THREAD

**Issue by RkcCorian** [LesTR/homeassistant-minimalistic-area-card#216]
### What happened?

Many thanks for your work, I started to setup for my house.

Since the last Core Update I have the trouble that lights which are off, as well as covers, that are closed are configured to be shown in gray color. Instead they are white. And after some time randomly a few are going to the expected gray. Which one is the same for all devices. So when some of them turn gray as expected I see the same on windows browser as well as for my mobile and tablet, so different devices but same behaviour

![Image](https://github.com/user-attachments/assets/0ea8483c-f51e-4f9c-9bb7-d3b4202c4b58)

### Card Version

1.2.27

### Home Assistant Version

Core: 2025.2.1; Supervisor: 2025.02.0; Operating System: 14.2; Frontend: 20250205.0

### Browser Version

Edge Version 132.0.2957.127 (Offizielles Build) (64-Bit), but also Android 14

### Relevant card config

```yaml
I have several cards, but one example:

type: custom:better-minimalistic-area-card
title: Schlafzimmer
area: schlafzimmer
image: /local/pictures/rooms/Schlafzimmer_Weich.jpg
hide_unavailable: false
shadow: false
state_color: true
darken_image: true
align:
  title: left
  sensors: left
  buttons: right
entities:
  - entity: sensor.schlafzimmerthermostat_temperature
    state_color: false
    color: "#FF6F22"
  - entity: sensor.schlafzimmerthermostat_humidity
    state_color: false
    color: "#2196F3"
  - entity: binary_sensor.balkontur
  - entity: light.schlafzimmerdeckenbeleuchtung
    tap_action:
      action: more-info
    double_tap_action:
      action: toggle
  - entity: light.schlafzimmerschrankbeleuchtung
    tap_action:
      action: more-info
    double_tap_action:
      action: toggle
  - entity: cover.schlafzimmerrollladen
grid_options:
  columns: 12
  rows: 3
card_mod:
  style: |
    .box .card-header {
      margin-top: 8px !important;
      font-weight: normal !important;
      font-size: 24px !important;
      #color: rgb(158, 158, 158) !important;
    }
    .box .sensors {      
      margin-left: 0px !important;
      margin-top: -10px !important;
      font-size: 16px !important;
      color: rgb(185, 185, 185) !important;
    }
    .box .sensors ha-icon-button  {
      zoom: 0.9 !important;
    }
    .box .buttons ha-icon-button  {
      zoom: 1.1 !important;
    }
```

### Relevant javascript log output

```shell

```
