### ISSUE TITLE
[Question]: is force_dialog just for buttons?

### ISSUE THREAD

**Issue by simowilso** [LesTR/homeassistant-minimalistic-area-card#234]
### What happened?

Eg can it be used for lights? In our household we have one less-abled user who sometimes eg turns lights on/off by mistake. (Actually we all do it) Ideally it would be nice to have an option to require confirmation for anything that can be turned on or off. 

### Card Version

1.2.29

### HomeAssistant Version

2025.2.2

### Relevant card config

```yaml

```

### Relevant log output

```shell

```

**Comment by LesTR** [comment]
No, it should not. I just checked it on one of my switches, and it works as expected.
```yaml
  - entity: switch.bathroom_electric_heating_switch
    section: sensors
    force_dialog: true
```
It shows dialog instead of calling toggle (the default). Can you share your settings?
