### ISSUE TITLE
[Bug]: Entity state color not working

### ISSUE THREAD

**Issue by CaptainKey3s** [LesTR/homeassistant-minimalistic-area-card#250]
### What happened?

The entity state color change is not working. In the last version everything was fine. Now the state color has no effect and the entity only shows the default color.

### Card Version

1.2.31

### Home Assistant Version

2025.2.5

### Browser Version

IOS App, Edge

### Relevant card config

```yaml
type: custom:better-minimalistic-area-card
title: Wohnzimmer
image: /local/Wohnzimmer.jpeg
rows: 2.2
columns: 6
hide_unavailable: false
darken_image: true
tap_action:
  action: navigate
  navigation_path: /lovelace/wohnzimmer
entities:
  - entity: climate.heizung_wohnzimmer
    tap_action:
      action: more-info
  - entity: switch.luftbefeuchter_power
    icon: phu:essential-oil-diffuser-alt
    state:
      - value: "on"
        color: teal
  - entity: light.wohnzimmerlampe
    icon: phu:uplighter
    state:
      - value: "on"
        color: orange
  - sensor.temperatur_wohnzimmer_offset
  - sensor.luftfeuchtigkeit_wohnzimmer_offset
  - entity: binary_sensor.fenstersensor_wohnzimmer_opening
    state:
      - value: "on"
        color: red
        icon: mdi:window-open-variant
```

### Relevant javascript log output

```shell

```
