### ISSUE TITLE
[Bug]: Small misalignment lights

### ISSUE THREAD

**Issue by BeFygo** [LesTR/homeassistant-minimalistic-area-card#275]
### What happened?

A Small misalignment occurs on mobile (smaller screen) when multiple sensors take extra space.

On the screenshot I made a circle in red to show the issue(3 sensors), in blue its how it should be (2 sensors).

![Image](https://github.com/user-attachments/assets/55b83d15-22cb-4773-80e1-736cdcd25bfc)

### Card Version

1.2.34

### Home Assistant Version

2025.4.0

### Browser Version

app

### Relevant card config

```yaml
type: custom:minimalistic-area-card
title: Woonkamer
area: woonkamer
show_area_icon: true
shadow: false
hide_unavailable: true
state_color: true
entity_type: auto
align:
  title: left
  sensors: left
  buttons: right
  title_entities: right
tap_action:
  action: navigate
  navigation_path: /dashboard-thuis/Woonkamer
entities:
  - entity: media_player.living_room_tv
    state_color: false
    shadow: false
    hide: false
    force_dialog: false
    darken_image: true
    section: auto
  - entity: media_player.speaker
  - entity: sensor.ml05_illuminance
    color: yellow
    tap_action:
      action: navigate
      navigation_path: /dashboard-thuis/Woonkamer
  - entity: sensor.thp09_humidity
    tap_action:
      action: navigate
      navigation_path: /dashboard-thuis/Woonkamer
    color: rgb(85, 120, 200)
  - entity: sensor.thp09_temperature
    color: rgba(225,95,46,255)
    tap_action:
      action: navigate
      navigation_path: /dashboard-thuis/Woonkamer
  - entity: light.woonkamer_links_lamp
  - entity: light.woonkamer_midden_lamp
  - entity: light.verdeelblok_1_l1
    tap_action:
      action: toggle
  - entity: climate.living
    hide: ${hass.states['climate.living'].state === 'off'}
    tap_action:
      action: none
    hold_action:
      action: more-info
grid_options:
  columns: 6
  rows: 2
```

### Relevant javascript log output

```shell

```
