### ISSUE TITLE
[Question]: tap action has no "hand" for link

### ISSUE THREAD

**Issue by titro** [LesTR/homeassistant-minimalistic-area-card#281]
### What happened?

currently if a tap action for navigation is configured, there is no "hand" when hovering over the card so you might think, there is no functionality for clicking

### Card Version

1.2.35

### HomeAssistant Version

2025.4.0

### Relevant card config

```yaml
type: custom:better-minimalistic-area-card
title: Wohnzimmer
area: wohnzimmer
hide_unavailable: false
tap_action:
  action: navigate
  navigation_path: /dashboard-home/wohnzimmer
```

### Relevant log output

```shell

```
