### ISSUE TITLE
[Question]: State color also for the text

### ISSUE THREAD

**Issue by titro** [LesTR/homeassistant-minimalistic-area-card#282]
### What happened?

you can only control the icon color with the state color. it would be great to also change the text color of the entity with the state 

### Card Version

v1.2.35

### HomeAssistant Version

2025.4.0

### Relevant card config

```yaml
state:
      - value: 60
        operator: ">"
        color: red
```

### Relevant log output

```shell

```
