### ISSUE TITLE
[Question]: "New" options for entities are not kept in yaml

### ISSUE THREAD

**Issue by indigomejor** [LesTR/homeassistant-minimalistic-area-card#315]
### What happened?

Hi LesTR, 

at first let me tell you that your take on minimalistic are card is much appriciated!

However, I have issues with using all the new options for entities. When written in the yaml configuration of the card, they act right, in the text at least, no changes are visible in the visual preview. 

After saving, the entity I tried to adjust disappears totally and in yaml its then shown as:
`- sensor.smart_plug color` instead of 
`- sensor.smart_plug (here should be enter and proper syntax...) color: blue`
happens also for some styling options... see the screenshot, temp. sensor value is not visible at all, should be first:

![Image](https://github.com/user-attachments/assets/f4af176e-670f-4b24-a0cd-636b78447402)

The question is, did I do something wrong while installing? I have even deleted all data (in UI resources) for the original minimalistic area card and tried it again, with no luck. Thousnds of reloads, dozens of restarts, but still same issue.

Can you give me some tips how to resolve this, please? So I can use your excellent addition to HA in its fullest potential. 
Thank you!

### Card Version

1.2.36

### HomeAssistant Version

2025.5.2

### Relevant card config

```yaml
type: custom:better-minimalistic-area-card
title: Living Room
area: living_room
image: /local/img/living-room.jpg
state_color: true
icon: mdi:sofa-single-outline
show_area_icon: false
hide_unavailable: true
force_dialog: true
shadow: false
tap_action:
  action: nothing
style:
  color: white
  align:
    title: center
    sensors: left
    buttons: right
    title_entities: right
entities:
  - sensor.living_room_temperature_zigbee
  - sensor.living_room_humidity_zigbee
  - sensor.living_room_current_consumption
  - sensor.living_room_daily_energy_consumption
  - light.living_room_lamp
  - light.hue_play
  - media_player.televizka
  - media_player.living_room
  - switch.nas_plug
  - switch.playstation_5
  - sensor.plex_nas
grid_options:
  columns: 12
  rows: 3
```

### Relevant log output

```shell

```
