### ISSUE TITLE
[Bug]: 1.2.37 causes icons to cramp together

### ISSUE THREAD

**Issue by txzeenath** [LesTR/homeassistant-minimalistic-area-card#345]
### What happened?

![Image](https://github.com/user-attachments/assets/06162768-aaba-4bd0-b766-62865a774737)

![Image](https://github.com/user-attachments/assets/d576ed9e-b64c-481c-bec9-ffee6ee7cb0d)

1.2.36 vs 1.2.37

Not sure what could've changed to cause that. Seeing as the recent commits seem pretty minor.

### Card Version

1.2.37

### Home Assistant Version

HAOS Core 2025.6.1

### Browser Version

Chrome & Android App

### Relevant card config

```yaml
type: custom:better-minimalistic-area-card
title: Porch
area: Porch
icon: mdi:balcony
show_area_icon: true
hide_unavailable: true
darken_image: false
tap_action: none
shadow: false
style:
  shadow_color: black
  buttons_icon_size: 24px
  buttons_button_size: 24px
  sensors_icon_size: 16px
  sensors_button_size: 16px
align:
  title: left
  sensors: left
  buttons: left
  title_entities: right
entities:
  - entity: sensor.porch_temperature_2
    state:
      - value: "40"
        operator: <
        color: lightcyan
        icon: mdi:thermometer-low
      - value: "50"
        operator: <
        color: lightblue
        icon: mdi:thermometer-low
      - value: "75"
        operator: ">"
        color: lightsalmon
        icon: mdi:thermometer-high
      - value: "80"
        operator: ">"
        color: orange
        icon: mdi:thermometer-high
      - value: "90"
        operator: ">"
        color: tomato
        icon: mdi:thermometer-high
      - value: null
        operator: default
        color: var(--ha-better-minimalistic-area-card-color)
        icon: mdi:thermometer
  - binary_sensor.porch_sensor_motion
  - entity: sensor.porch_sensor_light_level
    show_state: false
    state:
      - operator: <
        value: 10
        color: rgb(169,169,169)
      - operator: <
        value: 20
        color: rgb(180,165,130)
      - operator: <
        value: 50
        color: rgb(190,155,90)
      - operator: <
        value: 100
        color: rgb(200,135,50)
      - operator: <
        value: 150
        color: rgb(220,115,30)
      - operator: <
        value: 200
        color: rgb(240,130,20)
      - operator: <
        value: 300
        color: rgb(250,180,20)
      - operator: <
        value: 400
        color: rgb(255,210,0)
      - operator: <
        value: 500
        color: rgb(255,235,0)
      - operator: ">="
        value: 500
        color: rgb(255,255,0)
  - entity: binary_sensor.front_door_sensor_access_control_window_door_is_open
    state:
      - value: "on"
        color: orange
        icon: mdi:door-open
      - value: "off"
        color: var(--ha-better-minimalistic-area-card-color)
        icon: mdi:door-closed
  - entity: lock.front_door_lock
    show_state: false
    section: sensors
    state_color: true
    state:
      - value: locked
        color: var(--ha-better-minimalistic-area-card-color)
        icon: mdi:lock-outline
      - value: unlocked
        color: red
        icon: mdi:lock-off-outline
  - entity: light.porch_lights
    state:
      - value: "on"
        icon: hue:bulb-classic
      - value: "off"
        icon: hue:bulb-classic-off
  - input_boolean.delivery_light
  - entity: binary_sensor.front_door_ding
    icon: mdi:camera-outline
    section: buttons
    tap_action:
      action: navigate
      navigation_path: /lovelace/front-door-camera-view
  - entity: automation.auto_porch_light
    section: title
    state:
      - value: "on"
        color: var(--ha-better-minimalistic-area-card-color)
        icon: mdi:robot-outline
      - value: "off"
        color: red
        icon: mdi:robot-dead-outline
grid_options:
  columns: 6.2
  rows: 2.5
card_mod:
  style: |
    ha-card {
      width: 100%;
    }
```

### Relevant javascript log output

```shell
No errors or warnings in the developer console for BMAC
```

**Comment by LesTR** [comment]
Yeah, I see. The size overrides broke this with the combination of left alignment. I'm not using it, that's why I miss that, sorry. I added that to my dev dashboard, so I'll catch it next time. I'll take a look at it when I have some time, but not sooner than this weekend.  As a workaround, you can use the older version or remove those settings:
```yaml
style:
  buttons_icon_size: 24px
  buttons_button_size: 24px
  sensors_icon_size: 16px
  sensors_button_size: 16px
```
