### ISSUE TITLE
[Bug]: button icon size not updating

### ISSUE THREAD

**Issue by lennon101** [LesTR/homeassistant-minimalistic-area-card#346]
### What happened?

I'm not sure if I'm missing something or not (so I apologise in advance if this belongs in the questions section) but it seems like I can't get the button icon size to change. Here is my yaml for the card and a screenshot of the icons not updating. I've set the button icon size to `buttons_icon_size: 60px` as per the yaml below. But no change in the area card?  

![Image](https://github.com/user-attachments/assets/91ccc430-ad94-4292-ac40-e9f4a4c767e4)

### Card Version

1.2.37

### Home Assistant Version

2025.5.3

### Browser Version

Chrome and Brave 

### Relevant card config

```yaml
type: custom:better-minimalistic-area-card
title: Living Room
area: Living Room
icon: mdi:sofa
show_area_icon: true
hide_unavailable: false
state_color: true
darken_image: true
force_dialog: false
style:
  sensors_icon_size: 25px
  buttons_icon_size: 60px
align:
  title: left
  sensors: left
  buttons: right
  title_entities: right
tap_action:
  action: navigate
  navigation_path: /lovelace/living-room
entities:
  - entity: light.living_room_group
  - entity: climate.living_room_aircon
  - entity: sensor.gw1100c_indoor_temperature
    color: red
  - entity: sensor.gw1100c_indoor_humidity
    color: blue
  - entity: binary_sensor.hallway_glass_sliding_door_contact
    icon: mdi:door
    state_color: true
    state:
      - value: "on"
        color: green
        icon: mdi:door-open
      - value: "off"
        color: red
        icon: mdi:door-closed
```

### Relevant javascript log output

```shell

```
