### ISSUE TITLE
Add support for Font Header resizing

### ISSUE THREAD

**Issue by oerix** [LesTR/homeassistant-minimalistic-area-card#51]
### What happened?

Would be great if you could add an option to adjust the font size for the card header. I think adding a css variable for card_mod would be a simpler way to integrate this.

Thanks

### Card Version

1.2.9

### HomeAssistant Version

2024.9

**Comment by LesTR** [comment]
It looks like you can already use the card_mod.
<img width="242" alt="image" src="https://github.com/user-attachments/assets/cc5f0e3a-0d41-4706-8423-b996a701885d">
```yaml
card_mod:
  style: |
    .card-header {
      color: red;
    }
```

Or do you mean something else?
