### ISSUE TITLE
[Question]:  lock.toggle

### ISSUE THREAD

**Issue by ZEROX7** [LesTR/homeassistant-minimalistic-area-card#71]
### What happened?

so for som reason my lock doesnt toggle on tap anymore is there a way to manually lock.open wehn state is locked and lock.unlock wehn entity is closed?

### Card Version

1.2.13

### HomeAssistant Version

2024.9.3

### Relevant card config

```yaml
- entity: lock.wohnungstur
    state:
      - value: unlocked
        icon: phu:nuki
      - value: locked
        icon: phu:nuki
```
