### ISSUE TITLE
[Question]: Hide using Template needs help

### ISSUE THREAD

**Issue by ZEROX7** [LesTR/homeassistant-minimalistic-area-card#92]
### What happened?

I would like to hide a entity wehn another is not home but it doesnt seem to work

### Card Version

1.2.16

### HomeAssistant Version

2024.10.1

### Relevant card config

```yaml
type: custom:minimalistic-area-card
title: Keova's Zimmer
area: keovas_zi
icon: hue:room-bedroom
show_icon: true
hide_unavailable: false
shadow: false
state_color: true
tap_action:
  action: navigate
  navigation_path: /dashboard-cast/keovas-zi
entities:
  - binary_sensor.fenster_keova_s_zimmer_alarm
  - sensor.keova_s_zimmer_temperatur
  - sensor.keova_s_zimmer_luftfeuchtigkeit
  - climate.hk_keova_s_zimmer
  - entity: remote.gundam_projector
    state:
      - value: "on"
        icon: mdi:projector
        hide: false
      - value: "off"
        icon: mdi:projector-off
        hide: false
    hide: ${hass.states['device_tracker.samsungprojector'].state === 'not_home'}
    tap_action:
      action: perform-action
      perform_action: remote.toggle
      target:
        entity_id: remote.gundam_projector
  - light.keova_s_zimmer
  - light.ecke_links
  - light.bett_links
  - light.bett_leiste
  - light.bett_rechts
  - light.ecke_rechts
layout_options:
  grid_columns: 4
  grid_rows: 2
```

**Comment by LesTR** [comment]
state overrides take precedence in this case. You need to put it into both settings, I think it should be:
```yaml
- entity: remote.gundam_projector
    state:
      - value: "on"
        icon: mdi:projector
        hide: ${hass.states['device_tracker.samsungprojector'].state === 'not_home'}
      - value: "off"
        icon: mdi:projector-off
        hide: ${hass.states['device_tracker.samsungprojector'].state === 'not_home'}
```
It's not optimal, the current default value should be from entity settings.

**Comment by LesTR** [comment]
GH automatically closed the issue :-/ Since v1.2.17 you should be able to use:
```yaml
- entity: remote.gundam_projector
    state:
      - value: "on"
        icon: mdi:projector
      - value: "off"
        icon: mdi:projector-off
    hide: ${hass.states['device_tracker.samsungprojector'].state === 'not_home'}
```
